config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :tracks

  resources :mixes do
    resources :tracks
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions]

  # devise_scope :user do
  #   delete '/sign_out'  => 'devise/sessions#destroy', as: :destroy_user_session
  # end

  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign_in' => 'devise/sessions#create', :as => :user_session
    delete 'sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users do
    resources :mixes
  end

  # match 'signup' => 'users#new',        :as => :signup, via: :get
  # match 'logout' => 'sessions#destroy', :as => :logout, via: :get
  # match 'login' => 'sessions#new',      :as => :login,  via: :post

  root :to => 'mixes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mix.rb
class Mix < ApplicationRecord
  include ActiveModel::ForbiddenAttributesProtection

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  belongs_to :user
  has_many :tracks, -> { order "position ASC" }, dependent: :destroy

  accepts_nested_attributes_for :tracks, :reject_if => lambda { |t| t[:audio].blank? && t[:name].blank? }, allow_destroy: true
  mount_uploader :art, ArtUploader

  validates_presence_of :tracks, message: "can't be blank. Any good mix needs at least one track :)"
end

app/models/track.rb
class Track < ApplicationRecord
  include ActiveModel::ForbiddenAttributesProtection

  belongs_to :mix

  acts_as_list scope: :mix
  mount_uploader :audio, AudioUploader

  def filename
    File.basename(audio.path)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :mixes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :provider, :uid])
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController

  before_action :set_mix, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :sort, only: :update

  respond_to :html, :json

  # GET /mixes
  # GET /mixes.json
  def index
    if params.has_key?(:user_id)
      @mixes = Mix.where(user_id: params[:user_id])
    else
      @mixes = Mix.all
    end

    respond_with @mixes
  end

  # GET /mixes/1
  # GET /mixes/1.json
  def show
    @tracks = @mix.tracks

    respond_with @mix
  end

  # GET /mixes/new
  # GET /mixes/new.json
  def new
    @mix = Mix.new

    @mix.tracks.build

    respond_with @mix
  end

  # GET /mixes/1/edit
  def edit
  end

  # POST /mixes
  # POST /mixes.json
  def create
    @mix = Mix.new(mix_params)

    respond_to do |format|
      if @mix.save
        current_user.mixes << @mix
        format.html { redirect_to @mix, notice: 'Mix was successfully created.' }
        format.json { render json: @mix, status: :created, location: @mix }
      else
        format.html { render action: "new" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixes/1
  # PUT /mixes/1.json
  def update
    respond_to do |format|
      if @mix.update_attributes(mix_params)
        format.html { redirect_to @mix, notice: 'Mix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix.destroy

    respond_to do |format|
      format.html { redirect_to mixes_url }
      format.json { head :no_content }
    end
  end

  def sort
    @mix.tracks.each do |track|
      track.update_attribute :position, track_positions.index(track.id.to_s) + 1
    end
  end

private

  def set_mix
    @mix = Mix.friendly.find(params[:id])
  end

  def track_positions
    arr = Array.new
    params[:mix][:tracks_attributes].to_a.each do |hash|
      arr.push(hash[1]["id"])
    end
    arr
  end

  def mix_params
    params.require(:mix).permit(
      :id,
      :title,
      :description,
      :user_id,
      :art,
      :art_cache,
      :remove_art,
      tracks_attributes: [
        :id,
        :name,
        :artist,
        :mix_id,
        :audio,
        :position,
        :_destroy
      ]
    )
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end

private

  def track_params
    params.require(:track).permit(
      :id,
      :mix_id,
      :artist,
      :name,
      :audio,
      :position,
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join(",")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MinxTape" %></title>

    <%= stylesheet_link_tag "application" %>
    <link href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      if (window.location.hash && window.location.hash == '#_=_') {
        if (window.history && history.pushState) {
          window.history.pushState('', document.title, window.location.pathname);
        }
      }
    </script>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "shared/navigation" %>

    <%= render "shared/alerts" %>

    <%= render "shared/breadcrumbs" %>

    <main class="grid-container">

      <div class="grid-x grid-padding-x">
        <div class="cell">

          <%= yield %>

        </div>
      </div>

    </main>

    <%= render "shared/footer" %>

    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/jsmediatags/3.9.0/jsmediatags.min.js" %>
  </body>
</html>

app/views/mixes/_form.html.erb
<%= form_for @mix, :html => {:multipart => true} do |f| %>
  <% if @mix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mix.errors.count, "error") %> prohibited this mix from being saved:</h2>

      <ul>
      <% @mix.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, class: "ui-hidden-accessible" %>
    <%= f.text_field :title, placeholder: "Give it a name!" %>
  </div>

  <fieldset class="fieldset">
    <legend>Track Listing</legend>
    <div id="nested-tracks-form">
      <%= f.nested_fields_for :tracks do |track_form| %>
        <%= render "track", track_form: track_form %>
      <% end %>
    </div>
    <%= f.add_nested_fields_link :tracks, "Add a track", class: "button success" %>
  </fieldset>

  <div class="field">
    <%= f.label :description, class: "ui-hidden-accessible" %>
    <%= f.text_area :description, placeholder: "Any thoughts about this mix?" %>
  </div>

  <fieldset class="fieldset art">
    <legend>Artwork</legend>
    <div class="field">
      <%= image_tag(@mix.art.thumb.url) if @mix.art? %>
    </div>
    <div class="field">
      <%= f.file_field :art, accept: "image/jpeg,image/gif,image/png" %>
      <%= f.hidden_field :art_cache %>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit "Save Mix", class: "button radius success save-mix" %>
  </div>

<% end %>

app/views/mixes/_track.html.erb
<div class="track-input">
  <div class="input-group">
    <span class="input-group-label fi-list"></span>
    <%= track_form.text_field :name, placeholder: "Song - Artist", class: "input-group-field" %>
    <div class="input-group-button">
      <%= link_to 'Cancel', "#", class: "alert button cancel-edit-audio-file hidden", id: "cancel-edit-audio-file-#{track_form.object.id}", data: { target: track_form.object.id } %>
      <%= link_to "Edit", "#", class: "button edit-audio-file", id: "edit-audio-file-#{track_form.object.id}", style: "#{ 'display: none' if track_form.object.audio.blank? }", data: { target: track_form.object.id } %>
    </div>
  </div>
  <div class="input-group audio-file-uploader <%= 'hidden' unless track_form.object.audio.blank? %>" id="audio-file-<%= track_form.object.id %>">
    <%= track_form.file_field :audio, accept: "audio/mpeg,audio/mpeg3,audio/x-mpeg-3,audio/ogg,audio/mp4", class: "audio-file-upload-field" %>
    <div class="input-group-button">
      <%= track_form.remove_nested_fields_link '<span class="fi-trash small"></span>'.html_safe, class: "alert button audio-file-trash" %>
    </div>
  </div>

</div>

app/views/mixes/edit.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to "All Mixes", mixes_path %></li>
  <li><%= link_to @mix.title, mix_path(@mix) %></a></li>
  <li class="disabled">
    <span class="show-for-sr">Current: </span> Editing mix
  </li>
<% end %>

<%= render "form" %>

<%= link_to "Back", mixes_path, class: "button" %>

app/views/mixes/index.html.erb
<div class="grid-x grid-padding-x">
  <div class="cell medium-10 medium-offset-1 large-8 large-offset-2">
    <div class="grid-x grid-padding-x minxtape-intro">
      <div class="cell small-4">
        <%= image_tag "tape.jpg" %>
      </div>
      <div class="cell small-8">
        <% if user_signed_in? %>
          <%= link_to "+ Create a Mix Tape", new_user_mix_path(current_user), class: "button new-mix success" %>
        <% elsif %>
          <p>A new old school way to share music.<br><%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> to get started.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="grid-x grid-padding-x large-up-4 medium-up-3 small-up-2 mix-list">
  <% @mixes.each do |mix| %>
    <div class="cell">
      <article style="background-image: url(<%= mix.art.thumb.url %>);" class="mix">
        <a href="<%= mix_path(mix) %>">
          <header>
            <h1><%= mix.title %></h1>
          </header>
        </a>
      </article>
    </div>
  <% end %>
</div>

app/views/mixes/new.html.erb
<% content_for :breadcrumbs do %>
  <li><%= link_to 'All Mixes', mixes_path %></li>
  <li class="disabled">
    <span class="show-for-sr">Current: </span> New mix
  </li>
<% end %>

<h1>New mix</h1>

<%= render 'form' %>

<%= link_to 'Back', mixes_path, class: "button" %>

app/views/mixes/show.html.erb
<% content_for :title, @mix.title + ' • MinxTape' %>

<% content_for :breadcrumbs do %>
  <li><%= link_to 'All Mixes', mixes_path %></li>
  <li class="unavailable">
    <span class="show-for-sr">Current: </span> <%= @mix.title %>
  </li>
<% end %>

<article style="background-image: url(<%= @mix.art.thumb.url %>);" class="mix">
  <header>
    <h1><%= @mix.title %></h1>
    <p><%= @mix.description %></p>
    <% if user_signed_in? && (@mix.user == current_user) %>
      <div class="admin-actions">
        <%= link_to '<i class="fi-pencil"></i>'.html_safe, edit_mix_path(@mix), class: "button " %>
        <%= link_to '<i class="fi-trash"></i>'.html_safe, @mix, method: :delete, class: "button alert", data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  </header>
  <div class="audio-player-wrapper">
    <audio controls controlsList="nodownload" preload="metadata" id="minxtape-player" data-position="1">
      <source src="<%= @tracks.first.audio.url %>" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>
  </div>
  <ul class="track-list">
    <%= render @tracks %>
  </ul>
  <div class="overlay"></div>
</article>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="success callout" data-closable>
    <h5><%= notice %></h5>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif alert %>
  <div class="alert callout" data-closable>
    <h5><%= alert %></h5>
    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_breadcrumbs.html.erb
<% if content_for?(:breadcrumbs) %>
  <nav aria-label="You are here:" role="navigation">

  	<div class="grid-container">
      <div class="grid-x">
        <div class="cell medium-10 medium-offset-1 small-12">

          <ul class="breadcrumbs">

            <%= yield :breadcrumbs %>

          </ul>

        </div>
      </div>
    </div>

  </nav>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<div class="logo-wrapper">
		<%= image_tag('tape-inverse.jpg', :width => '255') %>
		<h4>MinxTape</h4>
		<h5>Spread the love.</h5>
	</div>
</footer>

app/views/shared/_navigation.html.erb
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">
    <%= link_to 'MinxTape', root_path %>
  </div>
</div>

<nav class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><%= link_to 'MinxTape', root_path, class: "top-bar-title-link" %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'My Mixes', user_mixes_path(current_user) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <% if user_signed_in? %>
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
          <%= link_to current_user.email, "#" %>
          <ul class="menu vertical">
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="menu">
        <li><%= link_to "Log in", new_user_session_path, class: "button top-bar-login-link" %></li>
        <li><%= link_to "Sign up", new_user_registration_path, class: "button" %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :mix_id %><br />
    <%= f.number_field :mix_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<li data-source="<%= track.audio.url %>" data-position="<%= track.position %>" id="minxtape-track-<%= track.position %>">
  <span class="fi-sound hidden" id="minxtape-track-indicator-<%= track.position %>"></span>
  <a href="#" class="trigger-track"><%= track.name %></a>
</li>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Artist</th>
    <th>Mix</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= track.title %></td>
    <td><%= track.artist %></td>
    <td><%= track.mix_id %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @track.title %>
</p>

<p>
  <b>Artist:</b>
  <%= @track.artist %>
</p>

<p>
  <b>Mix:</b>
  <%= @track.mix_id %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>